import type { Metadata } from "next";
import "./globals.css";
import { bric } from "./font";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bric.className} antialiased h-dvh`}>{children}</body>
    </html>
  );
}
