import type { Metadata } from "next";
import "./globals.css";
import { bric } from "./font";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="scroll-smooth transition-all duration-500" lang="en">
      <body
        className={`${bric.className} circuit-wrapper antialiased relative `}
      >
        {/* Full-page background */}
        <div className="circuit-background -z-10"></div>

        {/* Foreground content */}
        <Navbar />
        <main className="relative z-10">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
